<a href="https://colab.research.google.com/github/sally03915/2026-AI-Analysis-Lab/blob/main/AI-FlowTransformation/Step1-Math/basic001_numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 👨‍🍳 딥러닝 요리 마스터 연습문제

---


### [문제 1] 함수 만들기: def vs lambda 🪄

입력값 $x$에 **3을 곱하고 5를 더하는** 자동 기계(함수)를 만들려고 합니다.

1. `def`를 사용하여 `triple_add`라는 이름의 함수를 만드세요.
2. `lambda`를 사용하여 같은 기능을 하는 `fast_triple`이라는 변수를 만드세요.
3. 두 함수에 각각 `10`을 넣었을 때의 결과값을 출력하세요.

In [4]:
# 1. def 정석 함수
def triple_add(x):
    return x * 3 + 5

# 2. lambda 간편 함수
fast_triple = lambda x: x * 3 + 5

# 3. 결과 출력
print("def 결과:", triple_add(10))     # 결과: 35
print("lambda 결과:", fast_triple(10)) # 결과: 35

def 결과: 35
lambda 결과: 35


<br/>
<br/>
<br/>

### [문제 2] 재료 손질: range로 번호표 뽑기 🎟️

다음 결과 배열이 정확히 나오도록 `range()`와 `list()`를 조합하여 코드를 완성하세요.

* `list1` 결과: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`
* `list2` 결과: `[10, 20, 30]`


In [5]:
# 0부터 10 미만(9)까지 1씩 증가
list1 = list(range(10))

# 10부터 40 미만(30)까지 10씩 증가
list2 = list(range(10, 40, 10))

print("list1:", list1)
print("list2:", list2)

list1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
list2: [10, 20, 30]


<br/>
<br/>
<br/>

### [문제 3] 모양 맞추기: Numpy Reshape 🍱

`data = np.arange(12)`로 만든 12개의 재료가 있습니다. 이 재료들을 가지고 다음 3가지 모양의 접시(**Shape**)에 나누어 담는 코드를 작성하세요.

1. **3행 4열** (3x4)
2. **6행 2열** (6x2)
3. **2행 6열** (2x6)

In [6]:
import numpy as np

data = np.arange(12)

print("1) 3행 4열:\n", data.reshape(3, 4))
print("\n2) 6행 2열:\n", data.reshape(6, 2))
print("\n3) 2행 6열:\n", data.reshape(2, 6))

1) 3행 4열:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2) 6행 2열:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

3) 2행 6열:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


<br/>
<br/>
<br/>

### [문제 4] 정밀 계량: arange vs linspace ⚖️

다음 두 코드의 차이를 코드를 실행하지 않고 머리로 먼저 예측해 보세요!

1. `np.arange(0, 10, 3)`의 결과값은 무엇일까요?
2. `np.linspace(0, 10, 6)`를 사용하면 **총 몇 개의 숫자**가 생성되며, 숫자와 숫자 사이의 간격(Step)은 얼마일까요?



<해설>

1. **`np.arange(0, 10, 3)` 결과:** `[0, 3, 6, 9]`
* **해설:** 0부터 시작해서 10 '미만'까지 3씩 건너뛰며 숫자를 생성합니다.


2. **`np.linspace(0, 10, 6)` 결과:** 총 **6개**의 숫자가 생성되며, 간격은 **2.0**입니다.
* **해설:** 0부터 10까지 딱 6개의 숫자를 찍어야 하므로 구간(틈)은 $6 - 1 = 5$개가 생깁니다. 전체 길이 10을 5로 나누면 간격은 $\frac{10}{5} = 2$가 됩니다.
* **실제 생성 값:** `[0., 2., 4., 6., 8., 10.]`

1. `[0, 3, 6, 9]` (0부터 10 미만까지 3씩 증가)
2. 6개의 숫자가 생성됨. 간격: $(10 - 0) / (6 - 1) = 10 / 5 = 2$

<br/>
<br/>
<br/>

### [문제 5] 응용: 셰프의 계산기 🧮

앞서 배운 정밀 계량 공식을 활용해 보는 문제입니다.
`np.linspace(0, 20, 5)`를 사용하면 어떤 숫자 5개가 생성될지, 아래 공식을 이용해 간격을 구하고 최종 배열을 직접 계산해 보세요.

$$\text{간격} = \frac{\text{끝값} - \text{시작값}}{\text{개수} - 1}$$



* **간격 계산:**

$$\text{간격} = \frac{20 - 0}{5 - 1} = \frac{20}{4} = 5.0$$


* **최종 결과:** 시작값 0부터 5.0씩 더해가며 5개의 숫자를 채웁니다.

$$\rightarrow \text{[0.0, 5.0, 10.0, 15.0, 20.0]}$$